select * from customer limit 20

-- How much total revenue is generated by male customers compared to female customers?
select "Gender" , SUM("Purchase Amount (USD)") as revenue
from customer
group by "Gender"

-- Which customers used a discount but still spent more than the overall average purchase amount?
select "Customer ID" , "Purchase Amount (USD)"
from customer
where "Discount Applied"='Yes' 

-- Which are the top 5 products with the highest average review ratings?
SELECT "Item Purchased",
       ROUND(AVG("Review Rating"::numeric), 2) AS avg_product_rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;

-- How do the average purchase amounts differ between Standard Shipping and Express Shipping?
SELECT "Shipping Type",
       ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_purchase_amount
FROM customer
WHERE "Shipping Type" IN ('Standard', 'Express')
GROUP BY "Shipping Type";

-- Do subscribed customers spend more? Compare the average spending and total revenue of subscribers vs. non-subscribers.
SELECT "Subscription Status",
       COUNT("Customer ID") AS total_customers,
       ROUND(AVG("Purchase Amount (USD)"), 2) AS avg_spend,
       ROUND(SUM("Purchase Amount (USD)"), 2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;


-- Which 5 products have the highest percentage of purchases made with discounts?
SELECT "Item Purchased",
       ROUND(
            100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)
            / COUNT(*), 2
       ) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal groups based on their number of past purchases and show the count in each segment.
WITH customer_type AS (
    SELECT "Customer ID",
           "Previous Purchases",
           CASE
               WHEN "Previous Purchases" = 1 THEN 'New'
               WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- What are the top 3 most frequently purchased products within each product category?
WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT item_rank,
       "Category",
       "Item Purchased",
       total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Are repeat customers (those with more than 5 previous purchases) more likely to be subscribers?
SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";

-- How much revenue does each age group contribute to the total sales?
SELECT "Age",
       SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue DESC;
